spring:
  application:
    name: CarParkingSystem
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60000

app:
  system:
    run:
      method: scheduler
    input:
      file:
        location: "/inputs"
    vehicle:
      types:
        - kind: "car"
          fee: 2.00
        - kind: "motorcycle"
          fee: 1.00
  redis:
    embedded: true
