spring:
  application:
    name: CarParkingSystem
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 60000

app:
  system:
    input:
      file:
        location: "/inputs"
    output:
      method: "scheduler"
      file:
        enabled: true
        location: "/outputs"
    vehicle:
      types:
        - kind: "car"
          fee: 2.00
          index: 0
          lotName: "CarLot"
        - kind: "motorcycle"
          fee: 1.00
          index: 1
          lotName: "MotorcycleLot"
  redis:
    embedded: true
